tests: enhanced test suite to include legacy IDs

diff --git a/tests/softhsm b/tests/softhsm
--- a/tests/softhsm
+++ b/tests/softhsm
@@ -27,9 +27,27 @@ sed -e "s|@MODULE_PATH@|${ADDITIONAL_PARAM}|g" -e "s|@ENGINE_PATH@|../src/.libs/
 
 export OPENSSL_ENGINES="../src/.libs/"
 
-./evp-sign engines.cnf "pkcs11:model=SoftHSM%20v2;manufacturer=SoftHSM%20project;token=libp11-test;id=%00%01%02%03;object=server-key;type=private;pin-value=1234" ${ADDITIONAL_PARAM}
+./evp-sign false engines.cnf "pkcs11:model=SoftHSM%20v2;manufacturer=SoftHSM%20project;token=libp11-test;id=%00%01%02%03;object=server-key;type=private;pin-value=1234" ${ADDITIONAL_PARAM}
 if test $? != 0;then
-	echo "Basic PKCS #11 test test failed"
+	echo "Basic PKCS #11 test failed"
+	exit 1;
+fi
+
+./evp-sign 1234 engines.cnf "pkcs11:model=SoftHSM%20v2;manufacturer=SoftHSM%20project;token=libp11-test;id=%00%01%02%03;object=server-key;type=private" ${ADDITIONAL_PARAM}
+if test $? != 0;then
+	echo "Basic PKCS #11 test without pin-value failed"
+	exit 1;
+fi
+
+./evp-sign 1234 engines.cnf "label_server-key" ${ADDITIONAL_PARAM}
+if test $? != 0;then
+	echo "Basic PKCS #11 test with legacy name #1 failed"
+	exit 1;
+fi
+
+./evp-sign 1234 engines.cnf "id_00010203" ${ADDITIONAL_PARAM}
+if test $? != 0;then
+	echo "Basic PKCS #11 test with legacy name #2 failed"
 	exit 1;
 fi
 
